dsn: "postgres://127.0.0.1/gonvelope?sslmode=disable&user=postgres&password=postgres"
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
google_oauth:
  client_id: "somerandonId.apps.googleusercontent.com"
  client_secret: "GOCSPX-ARANDOMSECRETKEY"
  redirect_url: "http://localhost:8080/oauth2/google/callback"
  scopes: ["https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/gmail.send"]